name: Release
on:
  workflow_run:
    workflows: ['CI']
    branches: [main]
    types: [completed]

permissions:
  contents: write
  deployments: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: NPM Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: scttcper/github-actions/.github/workflows/npm-wasm-release.yml@main
    secrets:
      GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}